image: golang:1.9

cache:
  paths:
    - /apt-cache
    - /home/gitlab-runner/go/src/github.com
    - /home/gitlab-runner//go/src/golang.org
    - /home/gitlab-runner//go/src/google.golang.org
    - /home/gitlab-runner//go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - mkdir -p /home/gitlab-runner/go/src/gitlab.com/pantomath-io /home/gitlab-runner/go/src/_/builds
  - cp -r $CI_PROJECT_DIR /home/gitlab-runner/go/src/EcoPasport
  - ln -s /home/gitlab-runner/go/src/ /home/gitlab-runner/go/src/_/builds/
  - make dep

unit_tests:
  stage: test
  script:
    - make test

test:
  stage: test
  script:
    - whoami

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
  - master

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
    - demo-tools
