image: golang:1.9
cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - mkdir -p /go/src/ /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/
  - go get -u golang.org/x/lint/golint
  - echo $GOPATH
  - make dep

unit_tests:
  stage: test
  script:
    - make test
  tags:
    - go

race_detector:
  stage: test
  script:
    - make race
  tags:
    - go

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - eco-passport-back
  tags:
    - go
